### PR TITLE
Change build configuration

### PR DESCRIPTION
**Pull request by daisukes**
@muratams 

I have been working to find the best way to build NavCog3.
So far, I think this is the easiest way to manage to build the application.
Previously, we had to build bleloc, then HLPLocationManager with bleloc framework, and then NavCog3 with HLPLocationManager framework.
Recently, those built fat binaries cause issues especially with the iOS simulator on M1 (arm64) mac.

This change includes bleloc and HLPLocationManager as source pod libraries, which means we can build all the components at once.
Although there is another way to fix the build issue by using xcframeworks instead of fat binary frameworks, this change may reduce build-related issues.

Please let me know if you have any concerns with this change.

### CODE REVIEW

**Comment by muratams** [comment]
I could not build NavCog3 app on flat-build branch.


Xcode showed the following error message.
```
Lexical or Preprocessor Issue
'opencv2/opencv.hpp' file not found
```


Environment
- Xcode (Version 12.5.1 )


Reproduction procedure
1. `$ git clone https://github.com/hulop/NavCogIOSv3.git -b flat-build`
2. `$ cd NavCogIOSv3`
3. `$ pod install`
4. `$ open NavCog3.xcworkspace`
5. Configure build settings (e.g. Bundle Identifier)
6. Build NavCog3 target for Any iOS Device (arm64)

**Comment by daisukes** [comment]
hmm, I am using xcode 13 on M1 mac.
I will try it with 12.5.1.

Could you also try to remove all pod cache?

**Comment by muratams** [comment]
I removed pod cache by typing `pod cache clean --all` and deleted Xcode/DerivedData, but still I cannot build NavCog3 and Xcode shows the same error message.

**Comment by muratams** [comment]
I was using an old version of CocoaPods which does not support XCFrameworks using `vendored_frameworks`.
Updating CocoaPods solved the build problem.

**Pull request merged**
